import type { TutorialDefinition, TutorialScope } from './tutorial-types';

export const TUTORIAL_DEFINITIONS: Record<TutorialScope, TutorialDefinition> = {
  PIN_SETUP: {
    title: 'Security Setup',
    doneLabel: 'Done',
    steps: [
      {
        title: 'Set PIN',
        target: 'Settings > Security PIN button',
        description:
          'Configure 4-digit PIN so users can quickly unlock with PIN instead of password.',
        icon: '\uD83D\uDD12',
        targetKey: 'settings-set-pin',
        screen: 'SETTINGS',
      },
      {
        title: 'Open Receipt Layout',
        target: 'Settings > Open Receipt Layout Settings',
        description:
          'Configure what appears on printed receipts before going live.',
        icon: '\uD83E\uDDFE',
        targetKey: 'settings-open-layout',
        screen: 'SETTINGS',
      },
      {
        title: 'Download Branch Data',
        target: 'Settings > Redownload Branch Data',
        description:
          'Use this when web admin updates prices/master data for your branch.',
        icon: '\u2B73',
        targetKey: 'settings-redownload-data',
        screen: 'SETTINGS',
      },
      {
        title: 'Save Printer',
        target: 'Settings > Save Printer Settings',
        description:
          'After selecting printer type/details, save once and run Test Print.',
        icon: '\uD83D\uDDA8',
        targetKey: 'settings-save-printer',
        screen: 'SETTINGS',
      },
    ],
  },
  APP_WALKTHROUGH: {
    title: 'VPOS Walkthrough',
    doneLabel: 'Finish',
    steps: [
      {
        title: 'Sync Status',
        target: 'Home > Status card',
        description: 'Check if device is online before posting queued transactions.',
        icon: '\uD83D\uDCE1',
        targetKey: 'home-status',
        screen: 'HOME',
      },
      {
        title: 'Pending Queue',
        target: 'Home > Pending Sync card',
        description: 'Watch pending records to avoid missed transactions.',
        icon: '\uD83D\uDCE6',
        targetKey: 'home-pending',
        screen: 'HOME',
      },
      {
        title: 'POS Order Type',
        target: 'POS > Pickup/Delivery selector',
        description: 'Set sale mode before adding items.',
        icon: '\uD83D\uDED2',
        targetKey: 'pos-order-type',
        screen: 'POS',
      },
      {
        title: 'POS Customer',
        target: 'POS > Customer selector',
        description: 'Select a customer before payment.',
        icon: '\uD83D\uDC65',
        targetKey: 'pos-customer',
        screen: 'POS',
      },
      {
        title: 'POS Items',
        target: 'POS > Items selector',
        description: 'Pick products and set quantities/flow.',
        icon: '\u2795',
        targetKey: 'pos-item-selector',
        screen: 'POS',
      },
      {
        title: 'Proceed to Payment',
        target: 'POS > Proceed to Payment',
        description: 'Open payment modal and queue sale.',
        icon: '\u20B1',
        targetKey: 'pos-proceed-payment',
        screen: 'POS',
      },
      {
        title: 'Sales Search',
        target: 'Sales > Search bar',
        description: 'Find receipts, sale IDs, and customers quickly.',
        icon: '\uD83D\uDD0E',
        targetKey: 'sales-search',
        screen: 'SALES',
      },
      {
        title: 'Transfer Source',
        target: 'Transfer > Source Location',
        description: 'Start stock transfer from correct source.',
        icon: '\uD83D\uDCCD',
        targetKey: 'transfer-source',
        screen: 'TRANSFER',
      },
      {
        title: 'Expense Entry',
        target: 'Expense > Create Petty Cash Entry',
        description: 'Record cash IN/OUT during active shift.',
        icon: '\u20B1',
        targetKey: 'expense-create',
        screen: 'EXPENSE',
      },
      {
        title: 'Items Lookup',
        target: 'Items > Search bar',
        description: 'Search products by code, name, category, or brand.',
        icon: '\uD83D\uDD0E',
        targetKey: 'items-search',
        screen: 'ITEMS',
      },
      {
        title: 'Customer Lookup',
        target: 'Customers > Search bar',
        description: 'Open customer card to review balances and history.',
        icon: '\uD83D\uDC64',
        targetKey: 'customers-search',
        screen: 'CUSTOMERS',
      },
      {
        title: 'Shift Control',
        target: 'Shift > Start Duty',
        description: 'Open and close duty with cash variance tracking.',
        icon: '\u23F2',
        targetKey: 'shift-start-duty',
        screen: 'SHIFT',
      },
      {
        title: 'Printer Save',
        target: 'Settings > Save Printer Settings',
        description: 'Save printer config and run test print.',
        icon: '\uD83D\uDDA8',
        targetKey: 'settings-save-printer',
        screen: 'SETTINGS',
      },
    ],
  },
  HOME: {
    title: 'Home Guide',
    steps: [
      {
        title: 'Connection Status',
        target: 'Home > Status card',
        description: 'This shows if the device is online/offline with API connectivity.',
        icon: '\u2302',
        targetKey: 'home-status',
        screen: 'HOME',
      },
      {
        title: 'Pending Sync',
        target: 'Home > Pending Sync card',
        description: 'Use this to quickly monitor unsynced records while offline.',
        icon: '\uD83D\uDCE6',
        targetKey: 'home-pending',
        screen: 'HOME',
      },
      {
        title: 'Help Button',
        target: 'Header > ?',
        description: 'Tap this anytime to replay tutorial for the current screen.',
        icon: '\u2753',
        targetKey: 'module-help',
        screen: 'HOME',
      },
    ],
  },
  POS: {
    title: 'POS Guide',
    steps: [
      {
        title: 'Order Type',
        target: 'POS > Pickup/Delivery selector',
        description: 'Select whether this sale is Pickup or Delivery.',
        icon: '\uD83D\uDED2',
        targetKey: 'pos-order-type',
        screen: 'POS',
      },
      {
        title: 'Select Customer',
        target: 'POS > Customer selector',
        description: 'Customer is required before you can proceed to payment.',
        icon: '\uD83D\uDC65',
        targetKey: 'pos-customer',
        screen: 'POS',
      },
      {
        title: 'Add Items',
        target: 'POS > Items selector',
        description: 'Open item picker, choose products, then set quantity/flow in cart.',
        icon: '\u2795',
        targetKey: 'pos-item-selector',
        screen: 'POS',
      },
      {
        title: 'Proceed to Payment',
        target: 'POS > Proceed to Payment button',
        description: 'Review totals and open payment modal to complete sale.',
        icon: '\u20B1',
        targetKey: 'pos-proceed-payment',
        screen: 'POS',
      },
    ],
  },
  SALES: {
    title: 'Sales Guide',
    steps: [
      {
        title: 'Search Sales',
        target: 'Sales > Search bar',
        description: 'Filter by sale ID, receipt, customer, or location.',
        icon: '\uD83D\uDD0E',
        targetKey: 'sales-search',
        screen: 'SALES',
      },
      {
        title: 'Open Sale Details',
        target: 'Sales > First sale row',
        description: 'Tap a row to view full details, items, balances, and actions.',
        icon: '\uD83D\uDCC4',
        targetKey: 'sales-first-row',
        screen: 'SALES',
      },
      {
        title: 'Refresh',
        target: 'Sales > Refresh button',
        description: 'Refresh local list after sync or data changes.',
        icon: '\u21BB',
        targetKey: 'sales-refresh',
        screen: 'SALES',
      },
    ],
  },
  TRANSFER: {
    title: 'Transfer Guide',
    steps: [
      {
        title: 'Source Location',
        target: 'Transfer > Source Location',
        description: 'Pick where stock is coming from.',
        icon: '\uD83D\uDCCD',
        targetKey: 'transfer-source',
        screen: 'TRANSFER',
      },
      {
        title: 'Select Product',
        target: 'Transfer > Product selector',
        description: 'Choose item to transfer with FULL/EMPTY quantities.',
        icon: '\uD83D\uDCE6',
        targetKey: 'transfer-product',
        screen: 'TRANSFER',
      },
      {
        title: 'Queue Transfer',
        target: 'Transfer > Queue Transfer button',
        description: 'Save transfer locally and sync to post on server.',
        icon: '\u2194',
        targetKey: 'transfer-queue',
        screen: 'TRANSFER',
      },
    ],
  },
  EXPENSE: {
    title: 'Expense Guide',
    steps: [
      {
        title: 'Create Entry',
        target: 'Expense > Create Petty Cash Entry',
        description: 'Start a new IN/OUT petty cash record for active shift.',
        icon: '\u20B1',
        targetKey: 'expense-create',
        screen: 'EXPENSE',
      },
      {
        title: 'Filter Entries',
        target: 'Expense > ALL/OUT/IN filter',
        description: 'Use quick filters to review recent entries.',
        icon: '\u20B1',
        targetKey: 'expense-filter',
        screen: 'EXPENSE',
      },
    ],
  },
  ITEMS: {
    title: 'Items Guide',
    steps: [
      {
        title: 'Search Items',
        target: 'Items > Search bar',
        description: 'Search by item code, name, category, or brand.',
        icon: '\uD83D\uDD0E',
        targetKey: 'items-search',
        screen: 'ITEMS',
      },
      {
        title: 'Item Details',
        target: 'Items > First item card',
        description: 'Tap an item card to open linked details and pricing.',
        icon: '\u25A6',
        targetKey: 'items-first-card',
        screen: 'ITEMS',
      },
    ],
  },
  CUSTOMERS: {
    title: 'Customers Guide',
    steps: [
      {
        title: 'Search Customers',
        target: 'Customers > Search bar',
        description: 'Find customer quickly by name, code, or tier.',
        icon: '\uD83D\uDD0E',
        targetKey: 'customers-search',
        screen: 'CUSTOMERS',
      },
      {
        title: 'Open Transactions',
        target: 'Customers > First customer card',
        description: 'Tap a customer card to view sales/payment history.',
        icon: '\u263A',
        targetKey: 'customers-first-card',
        screen: 'CUSTOMERS',
      },
    ],
  },
  SHIFT: {
    title: 'Shift Guide',
    steps: [
      {
        title: 'Start Duty',
        target: 'Shift > Start Duty',
        description: 'Open duty with opening cash to begin transactions.',
        icon: '\u25B6',
        targetKey: 'shift-start-duty',
        screen: 'SHIFT',
      },
      {
        title: 'Cash Adjustment',
        target: 'Shift > Add Cash Adjustment',
        description: 'Record cash IN/OUT while duty is active.',
        icon: '\u20B1',
        targetKey: 'shift-cash-adjust',
        screen: 'SHIFT',
      },
      {
        title: 'End Duty',
        target: 'Shift > End Duty',
        description: 'Count actual cash and close shift with variance tracking.',
        icon: '\u25F7',
        targetKey: 'shift-end-duty',
        screen: 'SHIFT',
      },
    ],
  },
  SETTINGS: {
    title: 'Settings Guide',
    steps: [
      {
        title: 'Security PIN',
        target: 'Settings > Set/Change PIN',
        description:
          'Set a 4-digit PIN so cashier relogin is faster and safer than typing password every time.',
        icon: '\uD83D\uDD12',
        targetKey: 'settings-set-pin',
        screen: 'SETTINGS',
      },
      {
        title: 'Receipt Layout',
        target: 'Settings > Open Receipt Layout Settings',
        description:
          'Control receipt sections (logo, totals, footer, contact info) before printing for customers.',
        icon: '\uD83E\uDDFE',
        targetKey: 'settings-open-layout',
        screen: 'SETTINGS',
      },
      {
        title: 'Branch Data Sync',
        target: 'Settings > Redownload Branch Data',
        description:
          'Use this after web admin changes prices or master data for the selected branch.',
        icon: '\u2B73',
        targetKey: 'settings-redownload-data',
        screen: 'SETTINGS',
      },
      {
        title: 'Printer Save',
        target: 'Settings > Save Printer Settings',
        description:
          'After choosing printer type or address, save then run Test Print.',
        icon: '\uD83D\uDDA8',
        targetKey: 'settings-save-printer',
        screen: 'SETTINGS',
      },
      {
        title: 'Replay Help',
        target: 'Header > ?',
        description:
          'Tap this help button anytime to replay this walkthrough for the current module.',
        icon: '\u2753',
        targetKey: 'module-help',
        screen: 'SETTINGS',
      },
    ],
  },
};
